### ISSUE TITLE
Buttons in Edit-Mode Missing

### ISSUE THREAD

**Issue by thorsten79G** [Kaszub09/ZABAP_TABLE_EDIT#10]
Hello,
the project looks very nice. We are using ABAP 7.58 and I am facing the issue, that the buttons do not appear in the screenshot below (I made a screenshot from your GIT project)

![image](https://github.com/user-attachments/assets/dd74fe96-d406-4cc0-aaab-3f582b744eff)

It is possible to switch between edit and display mode. The update is working fine, too.
Unfortunately, it is not possible to add new data records or delete records due to the missing buttons.  

Do you have any ideas how to solve this problem?  I do not use SALV functions and so I do not have any idea.

Thanks and best regards
Thorsten

**Comment by Kaszub09** [comment]
Hi,
thanks for checking it out.
I don't have access to 7.58, but since those controls are in standard and (I think) displayed automatically by CL_GUI_ALV_GRID when a column is editable, I would speculate that maybe they changed how exactly this class works. It would be interesting to compare with existing reports that have editable columns and see if it's called differently in 7.58.

Anyway, I think method `cl_gui_alv_grid->set_ready_for_input` should explicitly make those buttons visible and fix the issue - please check the branch https://github.com/Kaszub09/ZABAP_TABLE_EDIT/tree/fix_edit_buttons_not_visible

**Comment by thorsten79G** [comment]
Hi Marcin,

this answer and fix were really fast.
Now it works. Thank you very much for your support.

Will you implement this fix in the main branch, too or is this fix only for higher versions.

Best regards
Thorsten
________________________________

ANDREAS STIHL AG & Co. KG
Kommanditgesellschaft mit Sitz in Waiblingen, HRA 260269, Amtsgericht Stuttgart
Persönlich haftende Gesellschafter: Hans Peter Stihl und STIHL AG mit Sitz in Waiblingen, HRB 263722, Amtsgericht Stuttgart
Vorstand der STIHL AG: Michael Traub (Vorstandsvorsitzender), Ingrid Jägering, Anke Kleinschmit, Dr. Michael Prochaska, Martin Schwarz

Vorsitzender des Aufsichtsrats der STIHL AG: Dr. Nikolas Stihl

____________________________________________________________________________

If you are not the legitimate recipient, please send the e-mail back and delete it
on your system. Any unauthorized use or transfer of confidential information
may have legal consequences.

____________________________________________________________________________

Wenn Sie nicht der rechtmäßige Empfänger sind, senden Sie uns bitte die E-Mail zurück
und löschen Sie sie auf Ihrem System. Die unberechtigte Nutzung oder Weitergabe von
vertraulichen Informationen kann strafrechtlich und zivilrechtlich verfolgt werden.

____________________________________________________________________________

**Comment by Kaszub09** [comment]
I merged it into main, since it should work all the same on older system.
