### ISSUE TITLE
short dump in tcode ZABAP_TABLE_EDIT_EX1

### ISSUE THREAD

**Issue by WegnerDan** [Kaszub09/ZABAP_TABLE_EDIT#2]
When testing with example 1 (tcode ZABAP_TABLE_EDIT_EX1) entering invalid values in "created by" creates a short dump in function module CHANGEDOCUMENT_MULTIPLE_CASE2.

Steps to reproduce:
Enter value 555 in "created by", then save:
![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/a18983d5-1958-4fd0-ae1f-3c9dc401a3b4)

![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/6efeb20d-99e0-40bb-af68-1baa35252bc4)

![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/0ef63525-7bb0-445b-980c-7d614ad46b14)

**Comment by Kaszub09** [comment]
Looks like the problem is with the version of 'CHANGEDOCUMENT_MULTIPLE_CASE2' in your system. In line 82 it's implied, that the last column with change indicator (U/I/D) is named 'KZ'. In my system it's a variable
![obraz](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/34368953/25c816a8-94e0-4c61-83db-e2df6fda215c)
which get's correctly recognized
![obraz](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/34368953/d0436add-8eee-459e-889a-84bfe9b6d6aa)
And when I took a look at generated Change Document function modules, it does append field named 'KZ'. So changing class zcl_zabap_table_fields->get_available_index_name to always return 'KZ' should solve the problem in your case.

I'm not sure yet about setting it in repo to always use 'KZ' since it will dump if a table already has this field (granted, it's probably a rare case), a problem which doesn't exists now.

**Comment by WegnerDan** [comment]
Thanks for the hint.

It seems there are two SAP Notes relevant to this.


This one changes the offending line:
https://me.sap.com/notes/2738374

This one should probably also be installed, but isn't directly related to this issue:
https://me.sap.com/notes/3131862

After implementing the notes, the short dump does not occur anymore.
Maybe add these notes into the readme of the repo?

![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/b7ea684c-2ba5-4aa4-abcb-84faac01cbf0)

**Comment by Kaszub09** [comment]
Good idea, thanks for finding more info and verifying solution. Added to readme.
