### ISSUE TITLE
Pass extension class as variable instead of class name

### ISSUE THREAD

**Issue by WegnerDan** [Kaszub09/ZABAP_TABLE_EDIT#5]
This is just a suggestion.

In the constructor of zcl_zabap_table_edit an extension class can be passed to parameter class_name. Instead of this, I think it would be better to just pass an instance of zif_zabap_table_edit to the constructor.

This would enable the caller to use existing instances or handle instance creation etc themselves. Also would enable to pass instances of local classes.

Even if creating a bespoke class, the caller can just pass `NEW zcl_some_extension( )` to the parameter.   

If the class does not implement interface zif_zabap_table_edit, syntax check will prevent activation.

What do you think?

**Comment by Kaszub09** [comment]
Well, yeah, it could be done this way. You can make it as optional, and create default empty implementation if not supplied. And create interface in a main program. I you think it's worth adding and could prepare the change, I can merge, no problem.

All in all it's probably a better design (easier to test, if there were any :P) and less restrictive. Altough for me the main use is via assigning t-code to call the main program with prefilled parameters (one for every table I need), and I think it's a rare case where you would do otherwise (maybe something like having report with list of tables and editing any one via double click? :P)

**Comment by WegnerDan** [comment]
It would only be a small change for your program ZABAP_TABLE_EDIT.

I've created a branch in my repo:
https://github.com/WegnerDan/ZABAP_TABLE_EDIT/commit/9c431adc0fac4ecf28f8a1a137f29019d66ec989

I am suggesting this, because it would make my life easier, in the use case I have planned for this.

**Comment by Kaszub09** [comment]
I've checked and it looks fine to me, so I went ahead and merged it. :)
